const prisma = require('../prisma/client');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const crypto = require('crypto');
const { supabase, hasSupabaseKeys } = require('../utils/supabase');

const VALID_ROLES = ['user', 'admin'];

const generateToken = (id, role) => {
  return jwt.sign({ id, role }, process.env.JWT_SECRET, {
    expiresIn: process.env.JWT_EXPIRE || '30d'
  });
};

const validatePasswordStrength = (password) => {
  if (password.length < 6) {
    return { valid: false, message: 'Password must be at least 6 characters.' };
  }
  if (!/[A-Z]/.test(password)) {
    return { valid: false, message: 'Password must contain at least one uppercase letter.' };
  }
  if (!/[0-9]/.test(password)) {
    return { valid: false, message: 'Password must contain at least one number.' };
  }
  if (!/[!@#$%^&*(),.?":{}|<>]/.test(password)) {
    return { valid: false, message: 'Password must contain at least one special character.' };
  }
  return { valid: true };
};

exports.signup = async (req, res) => {
  try {
    const { name, email, password, role, phone } = req.body;

    // Validate role
    const userRole = role || 'user';
    if (!VALID_ROLES.includes(userRole)) {
      return res.status(400).json({ success: false, message: 'Invalid role. Must be "user" or "admin".' });
    }

    // Normalize email or phone input
    let finalEmail = '';
    let finalPhone = '';
    let isPhoneSignup = false;

    if (email && email.includes('@')) {
      finalEmail = email.toLowerCase().trim();
      finalPhone = phone ? phone.trim() : '';
    } else if (email) {
      // Input entered in the email field was actually a phone number
      finalPhone = email.trim();
      finalEmail = `${finalPhone}@dineflow.com`;
      isPhoneSignup = true;
    } else if (phone) {
      finalPhone = phone.trim();
      finalEmail = `${finalPhone}@dineflow.com`;
      isPhoneSignup = true;
    }

    if (!name || !finalEmail || !password) {
      return res.status(400).json({ success: false, message: 'Please provide name, email or phone, and password.' });
    }

    const passCheck = validatePasswordStrength(password);
    if (!passCheck.valid) {
      return res.status(400).json({ success: false, message: passCheck.message });
    }

    // Check if user already exists
    const userExists = await prisma.user.findFirst({
      where: {
        OR: [
          { email: finalEmail },
          ...(finalPhone ? [{ phone: finalPhone }] : [])
        ]
      }
    });

    if (userExists) {
      const isEmailMatch = userExists.email === finalEmail;
      const fieldUsed = isEmailMatch ? 'email' : 'phone number';
      return res.status(400).json({ success: false, message: `An account with this ${fieldUsed} already exists.` });
    }

    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash(password, salt);

    let userId;
    const verificationToken = crypto.randomBytes(32).toString('hex');

    if (hasSupabaseKeys) {
      // Create user in Supabase Auth using service client
      const { data, error } = await supabase.auth.admin.createUser({
        email: finalEmail,
        password,
        email_confirm: true,
        user_metadata: { name, role: userRole, phone: finalPhone }
      });

      if (error) {
        return res.status(400).json({ success: false, message: `Supabase registration failed: ${error.message}` });
      }

      userId = data.user.id;
    }

    const user = await prisma.user.create({
      data: {
        id: userId, // Uses Supabase ID if present, otherwise defaults to autogenerated UUID
        name,
        email: finalEmail,
        password: hashedPassword,
        role: userRole,
        phone: finalPhone,
        emailVerified: isPhoneSignup ? true : false,
        verificationToken: isPhoneSignup ? '' : verificationToken
      }
    });

    const token = generateToken(user.id, user.role);
    user.password = undefined;

    // Email verification link simulation
    let verificationLink = '';
    if (!isPhoneSignup) {
      verificationLink = `${req.protocol}://${req.get('host')}/api/auth/verify-email?token=${verificationToken}`;
      console.log(`\n📧 [EMAIL VERIFICATION LINK SENT] For ${finalEmail}: \n🔗 ${verificationLink}\n`);
    }

    res.status(201).json({ 
      success: true, 
      token, 
      user,
      _devDebug: !isPhoneSignup ? {
        verificationToken,
        verificationLink
      } : undefined
    });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
};

exports.login = async (req, res) => {
  try {
    const { email, password, role } = req.body;
    
    if (!email || !password) {
      return res.status(400).json({ success: false, message: 'Please provide email/phone and password.' });
    }

    const normalizedInput = email.toLowerCase().trim();
    let user;
    if (normalizedInput.includes('@')) {
      user = await prisma.user.findUnique({ where: { email: normalizedInput } });
    } else {
      user = await prisma.user.findFirst({
        where: {
          OR: [
            { phone: normalizedInput },
            { email: `${normalizedInput}@dineflow.com` }
          ]
        }
      });
    }

    // Check account lockout first
    if (user && user.lockUntil && user.lockUntil > new Date()) {
      const minutesLeft = Math.ceil((new Date(user.lockUntil) - new Date()) / 1000 / 60);
      return res.status(403).json({
        success: false,
        message: `This account is temporarily locked due to multiple failed login attempts. Please try again in ${minutesLeft} minute(s).`
      });
    }

    let credentialsValid = false;

    if (hasSupabaseKeys) {
      // Verify login credentials using Supabase Auth
      const { data, error } = await supabase.auth.signInWithPassword({
        email: user ? user.email : normalizedInput,
        password
      });

      if (!error) {
        credentialsValid = true;
        // Check if user exists by Supabase UUID just in case email mismatched or has different casing
        if (!user) {
          user = await prisma.user.findUnique({ where: { id: data.user.id } });
        }

        // Sync user to database table if missing
        if (!user) {
          const metadata = data.user.user_metadata || {};
          const userEmail = data.user.email || (user ? user.email : (normalizedInput.includes('@') ? normalizedInput : `${normalizedInput}@dineflow.com`));
          user = await prisma.user.create({
            data: {
              id: data.user.id,
              name: metadata.name || 'User',
              email: userEmail,
              password: '',
              role: metadata.role || 'user',
              phone: metadata.phone || (normalizedInput.includes('@') ? '' : normalizedInput),
              emailVerified: true // Supabase accounts synced can be verified by default
            }
          });
        } else {
          // If user was found but email is different/casing is different, sync email
          const targetEmail = data.user.email || user.email;
          if (user.email !== targetEmail) {
            user = await prisma.user.update({
              where: { id: user.id },
              data: { email: targetEmail }
            });
          }
        }
      }
    } else {
      // Local fallback password verification
      if (user) {
        const isMatch = await bcrypt.compare(password, user.password);
        if (isMatch) {
          credentialsValid = true;
        }
      }
    }

    if (!credentialsValid) {
      if (user) {
        // Increment failed attempts
        const attempts = user.loginAttempts + 1;
        let lockUntil = null;
        let msg = 'Invalid credentials.';

        if (attempts >= 5) {
          lockUntil = new Date(Date.now() + 15 * 60 * 1000); // 15 minutes lock
          msg = 'Account locked due to 5 failed attempts. Please try again in 15 minutes.';
        } else {
          msg = `Invalid credentials. Remaining attempts before lockout: ${5 - attempts}`;
        }

        await prisma.user.update({
          where: { id: user.id },
          data: { loginAttempts: attempts, lockUntil }
        });

        return res.status(401).json({ success: false, message: msg });
      }

      return res.status(401).json({ success: false, message: 'Invalid credentials.' });
    }

    // Validate role matches sign-in type
    if (role && user.role !== role) {
      const expected = role === 'admin' ? 'admin' : 'customer';
      return res.status(403).json({ 
        success: false, 
        message: `This account is not registered as an ${expected}. Please use the correct sign-in page.` 
      });
    }

    // 2FA check bypassed as requested by user to disable 2-step verification.

    // Normal successful login without 2FA
    await prisma.user.update({
      where: { id: user.id },
      data: { loginAttempts: 0, lockUntil: null }
    });

    const token = generateToken(user.id, user.role);
    user.password = undefined;

    res.status(200).json({ success: true, token, user });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
};

exports.verifyOtp = async (req, res) => {
  try {
    const { email, otpCode } = req.body;
    if (!email || !otpCode) {
      return res.status(400).json({ success: false, message: 'Please provide email/phone and OTP code.' });
    }

    const normalizedInput = email.toLowerCase().trim();
    let user;
    if (normalizedInput.includes('@')) {
      user = await prisma.user.findUnique({ where: { email: normalizedInput } });
    } else {
      user = await prisma.user.findFirst({
        where: {
          OR: [
            { phone: normalizedInput },
            { email: `${normalizedInput}@dineflow.com` }
          ]
        }
      });
    }

    if (!user) {
      return res.status(404).json({ success: false, message: 'User not found.' });
    }

    // Check account lockout
    if (user.lockUntil && user.lockUntil > new Date()) {
      const minutesLeft = Math.ceil((new Date(user.lockUntil) - new Date()) / 1000 / 60);
      return res.status(403).json({
        success: false,
        message: `This account is temporarily locked. Please try again in ${minutesLeft} minute(s).`
      });
    }

    if (user.otpCode !== otpCode || !user.otpExpires || user.otpExpires < new Date()) {
      // Increment failed attempts as a failed verification counts
      const attempts = user.loginAttempts + 1;
      let lockUntil = null;
      let msg = 'Invalid or expired OTP code.';

      if (attempts >= 5) {
        lockUntil = new Date(Date.now() + 15 * 60 * 1000);
        msg = 'Invalid OTP. Account locked due to 5 failed attempts. Please try again in 15 minutes.';
      } else {
        msg = `Invalid OTP code. Remaining attempts before lockout: ${5 - attempts}`;
      }

      await prisma.user.update({
        where: { id: user.id },
        data: { loginAttempts: attempts, lockUntil }
      });

      return res.status(401).json({ success: false, message: msg });
    }

    // OTP Verified successfully
    await prisma.user.update({
      where: { id: user.id },
      data: { otpCode: '', otpExpires: null, loginAttempts: 0, lockUntil: null }
    });

    const token = generateToken(user.id, user.role);
    user.password = undefined;

    res.status(200).json({ success: true, token, user });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
};

exports.verifyEmail = async (req, res) => {
  try {
    const { token } = req.query;
    if (!token) {
      return res.status(400).send('<h1>Verification token is required.</h1>');
    }

    const user = await prisma.user.findFirst({
      where: { verificationToken: token }
    });

    if (!user) {
      return res.status(400).send('<h1>Invalid or expired verification token.</h1>');
    }

    await prisma.user.update({
      where: { id: user.id },
      data: { emailVerified: true, verificationToken: '' }
    });

    res.send(`
      <div style="font-family: 'Playfair Display', Georgia, serif; text-align: center; padding: 50px; background-color: #fcfbf7; min-height: 100vh; display: flex; flex-direction: column; align-items: center; justify-content: center; color: #1c1917;">
        <div style="border: 1px solid #e7e5e4; background-color: white; border-radius: 24px; padding: 40px; box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.05); max-width: 500px;">
          <div style="font-size: 48px; margin-bottom: 20px; color: #d4af37;">✓</div>
          <h1 style="font-size: 28px; margin-bottom: 10px;">Email Verified!</h1>
          <p style="font-size: 15px; color: #78716c; line-height: 1.5; margin-bottom: 30px;">Your email address has been successfully verified. You can now close this window and log in to DineFlow.</p>
          <a href="${process.env.FRONTEND_URL || 'http://localhost:5173'}/auth" style="background-color: #1c1917; color: #fcfbf7; padding: 12px 30px; border-radius: 12px; font-weight: bold; text-decoration: none; font-size: 14px;">Go to Sign In</a>
        </div>
      </div>
    `);
  } catch (err) {
    res.status(400).send(`<h1>Verification failed</h1><p>${err.message}</p>`);
  }
};

exports.toggle2FA = async (req, res) => {
  try {
    const { enabled } = req.body;
    if (enabled === undefined) {
      return res.status(400).json({ success: false, message: 'Please provide enabled parameter.' });
    }

    await prisma.user.update({
      where: { id: req.user.id },
      data: { twoFactorEnabled: enabled }
    });

    res.status(200).json({
      success: true,
      message: `Two-factor authentication has been ${enabled ? 'enabled' : 'disabled'} successfully.`
    });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
};

exports.getMe = async (req, res) => {
  try {
    const user = await prisma.user.findUnique({ where: { id: req.user.id } });
    user.password = undefined;
    res.status(200).json({ success: true, data: user });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
};

exports.updateProfile = async (req, res) => {
  try {
    const { name, email, phone, profilePicture } = req.body;
    const updateData = {};
    if (name !== undefined) updateData.name = name;
    if (phone !== undefined) updateData.phone = phone;
    if (profilePicture !== undefined) updateData.profilePicture = profilePicture;

    const normalizedEmail = email ? email.toLowerCase().trim() : undefined;
    if (normalizedEmail !== undefined) updateData.email = normalizedEmail;

    // Check if email already in use
    if (normalizedEmail && normalizedEmail !== req.user.email) {
      const emailExists = await prisma.user.findUnique({ where: { email: normalizedEmail } });
      if (emailExists) {
        return res.status(400).json({ success: false, message: 'An account with this email already exists.' });
      }
    }

    if (hasSupabaseKeys) {
      // Sync email/metadata to Supabase if it changed
      const supabaseUpdates = {};
      if (normalizedEmail && normalizedEmail !== req.user.email) supabaseUpdates.email = normalizedEmail;
      if (name) supabaseUpdates.data = { name };
      
      if (Object.keys(supabaseUpdates).length > 0) {
        const { error } = await supabase.auth.admin.updateUserById(req.user.id, supabaseUpdates);
        if (error) {
          return res.status(400).json({ success: false, message: `Supabase update failed: ${error.message}` });
        }
      }
    }

    const updatedUser = await prisma.user.update({
      where: { id: req.user.id },
      data: updateData
    });
    
    updatedUser.password = undefined;
    res.status(200).json({ success: true, data: updatedUser });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
};

exports.updatePassword = async (req, res) => {
  try {
    const { currentPassword, newPassword } = req.body;
    if (!currentPassword || !newPassword) {
      return res.status(400).json({ success: false, message: 'Please provide current and new passwords.' });
    }

    const passCheck = validatePasswordStrength(newPassword);
    if (!passCheck.valid) {
      return res.status(400).json({ success: false, message: passCheck.message });
    }

    const user = await prisma.user.findUnique({ where: { id: req.user.id } });

    if (hasSupabaseKeys) {
      // Update password in Supabase Auth
      const { error } = await supabase.auth.updateUser({ password: newPassword });
      if (error) {
        return res.status(400).json({ success: false, message: `Supabase password update failed: ${error.message}` });
      }
    }

    // Local password update (with comparison verify if local password was stored)
    if (user.password) {
      const isMatch = await bcrypt.compare(currentPassword, user.password);
      if (!isMatch) {
        return res.status(400).json({ success: false, message: 'Incorrect current password.' });
      }
    }

    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash(newPassword, salt);

    await prisma.user.update({
      where: { id: req.user.id },
      data: { password: hashedPassword }
    });

    res.status(200).json({ success: true, message: 'Password updated successfully.' });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
};

exports.verifyMyEmail = async (req, res) => {
  try {
    const updatedUser = await prisma.user.update({
      where: { id: req.user.id },
      data: { emailVerified: true }
    });
    res.status(200).json({ success: true, message: 'Email verified successfully.', data: updatedUser });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
};

exports.getBankAccount = async (req, res) => {
  try {
    const user = await prisma.user.findUnique({
      where: { id: req.user.id },
      select: {
        bankAccountName: true,
        bankAccountNumber: true,
        bankIfsc: true,
        bankName: true,
        bankBranch: true,
        bankAccountVerified: true
      }
    });
    res.status(200).json({ success: true, data: user });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
};

exports.updateBankAccount = async (req, res) => {
  try {
    const { bankAccountName, bankAccountNumber, bankIfsc, bankName, bankBranch, bankAccountVerified } = req.body;

    if (!bankAccountName || !bankAccountNumber || !bankIfsc) {
      return res.status(400).json({ success: false, message: 'Please provide Account Holder Name, Account Number, and IFSC.' });
    }

    // Validate Account Holder Name
    const nameTrimmed = bankAccountName.trim();
    if (nameTrimmed.length < 3) {
      return res.status(400).json({ success: false, message: 'Account Holder Name must be at least 3 characters.' });
    }
    if (/[0-9]/.test(nameTrimmed)) {
      return res.status(400).json({ success: false, message: 'Account Holder Name cannot contain numbers.' });
    }

    // Validate Account Number digits (9-18 digits)
    const accNum = bankAccountNumber.trim();
    if (!/^\d{9,18}$/.test(accNum)) {
      return res.status(400).json({ success: false, message: 'Bank Account Number must be between 9 and 18 digits.' });
    }

    // Block fake/dummy account numbers (like all same digits, or sequential)
    if (/^(\d)\1+$/.test(accNum)) {
      return res.status(400).json({ success: false, message: 'Invalid Account Number. Dummy accounts with identical numbers are not allowed.' });
    }
    if (['123456789', '1234567890', '0123456789', '987654321', '9876543210'].some(seq => accNum.includes(seq))) {
      return res.status(400).json({ success: false, message: 'Invalid Account Number. Sequential dummy numbers are not allowed.' });
    }

    // Validate IFSC format: 4 letters, 0, 6 characters (digits or letters)
    const ifsc = bankIfsc.trim().toUpperCase();
    if (!/^[A-Z]{4}0[A-Z0-9]{6}$/.test(ifsc)) {
      return res.status(400).json({ success: false, message: 'Invalid IFSC code format.' });
    }

    const updatedUser = await prisma.user.update({
      where: { id: req.user.id },
      data: {
        bankAccountName: nameTrimmed,
        bankAccountNumber: accNum,
        bankIfsc: ifsc,
        bankName: bankName ? bankName.trim() : null,
        bankBranch: bankBranch ? bankBranch.trim() : null,
        bankAccountVerified: !!bankAccountVerified
      }
    });

    res.status(200).json({
      success: true,
      message: 'Bank account settings updated successfully.',
      data: {
        bankAccountName: updatedUser.bankAccountName,
        bankAccountNumber: updatedUser.bankAccountNumber,
        bankIfsc: updatedUser.bankIfsc,
        bankName: updatedUser.bankName,
        bankBranch: updatedUser.bankBranch,
        bankAccountVerified: updatedUser.bankAccountVerified
      }
    });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
};

